config/routes.rb
Rails.application.routes.draw do

  resources :order_details

  resources :orders

  resources :customers

  resources :products

  resources :merchants

  resources :addresses

  resources :users

  root to: 'visitors#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Market', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to 'Sign out', signout_path %></li>
        <% else %>
            <li><%= link_to 'Sign in', signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
    <li><%= link_to 'Users', users_path %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Merchant<span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><a href="/merchants">List</a></li>
        <li class="divider"></li>
        <li><a href="/merchants/new">Create</a></li>
      </ul>
    </li>
<% end %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Customer<span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/customers">List</a></li>
    <li class="divider"></li>
    <li><a href="/customers/new">Create</a></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Order<span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/orders">List</a></li>
    <li class="divider"></li>
    <li><a href="/orders/new">Create</a></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Order details<span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/order_details">List</a></li>
    <li class="divider"></li>
    <li><a href="/order_details/new">Create</a></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Address<span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/addresses">List</a></li>
    <li class="divider"></li>
    <li><a href="/addresses/new">Create</a></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Products<span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/products">List</a></li>
    <li class="divider"></li>
    <li><a href="/products/new">Create</a></li>
  </ul>
</li>
</li>
<li><%= link_to 'About', page_path('about') %></li>
<li><a href="#">Contact</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Market</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Static navbar -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Market</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Merchant<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/merchants">List</a></li>
                        <li><a href="/merchants/new">Create</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Search</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Customer<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/customers">List</a></li>
                        <li><a href="/customers/new">Create</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Search</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Order<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/orders">List</a></li>
                        <li><a href="/orders/new">Create</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Search</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Order details<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/order_details">List</a></li>
                        <li class="divider"></li>
                        <li><a href="/order_details/new">Create</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Address<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/addresses">List</a></li>
                        <li class="divider"></li>
                        <li><a href="/addresses/new">Create</a></li>
                    </ul>
                </li>
                </li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
                <li><a href="../navbar-static-top/">Static top</a></li>
                <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>

<%= yield %>

</body>
</html>